name: Reassure Performance Tests

on:
  push:
    branches: [main_test]
  pull_request:
    branches: ['**']

jobs:
  perf-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run performance testing script
        run: '../../scripts/reassure-tests.sh'

      - name: Run Danger.js
        run: npm run danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
